# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-lasuite
  version: "0.0.12"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_lasuite-${{ version }}.tar.gz
  sha256: 9de348abdfe6b4f1e64f064ced4620c9dbc1e3a5d96550b6dcbeac544c23422e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - django >=5.0
    - djangorestframework >=3.15.2
    - mozilla-django-oidc >=4.0.1
    - joserfc >=1.0.4
    - requests >=2.32.3
    - requests-toolbelt >=1.0.0
    - pyjwt >=2.10.1

tests:
  - python:
      imports:
        - lasuite
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Django La Suite - A Django library
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/suitenumerique/django-lasuite

extra:
  recipe-maintainers:
    - rxm7706
