{% set name = "whylogs" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/whylogs-{{ version }}.tar.gz
  sha256: 79f5f6402fb5380ca1355b11951aff772825b7ded4e43296e1a64fb8ebc61ce6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - wheel
    - setuptools
    - poetry-core
  run:
    - python >=3.8
    - protobuf >=3.19.4
    - typing-extensions >=3.10
    - whylabs-client >=0.5.1,<1
    - whylogs-sketching >=3.4.1.dev3

test:
  imports:
    - whylogs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/whylabs/whylogs
  summary: Profile and monitor your ML data pipeline end-to-end
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - rxm7706
